### ISSUE TITLE
2.0.x only works with stanard helm repo, not with oci 

### ISSUE THREAD

**Issue by tosmi** [tjungbauer/openshift-clusterconfig-gitops#5]
using a chart version of 2.0.x does not work for oci images. helm searches for tag with that name in the registry. 

we could create a floating tag 2.0.x that points to the latest 2.0. version, but ...

either:
- create a comment explaining what needs to be done for oci helm regs
- or use a specific version

https://github.com/tjungbauer/openshift-clusterconfig-gitops/blob/a22535b1d2887f0c1c659b0fa34b0d1cc4b1fafe/base/init_app_of_apps/values.yaml#L45

**Comment by tjungbauer** [comment]
This is fixed with the new release
