### ISSUE TITLE
Typo in init_GitOps.sh

### ISSUE THREAD

**Issue by kastl-ars** [tjungbauer/openshift-clusterconfig-gitops#6]
https://github.com/tjungbauer/openshift-clusterconfig-gitops/blob/c26687dbd7154fcc6c876ecf24e48c9151c076df/init_GitOps.sh#L31

`Subscription does not exist already`

This should read `Subscription already exists` or `Subscription does exist already`, right?

**Comment by tjungbauer** [comment]
This is correct, it should be "does exist already". :)
 I fixed the typo. 

Thank you very much
